### ISSUE TITLE
NGINX  setup 🆘 

### ISSUE THREAD

**Issue by mrbeandev** [fastsitephp/fastsitephp#23]
i am running a domain with nginx webserver

how do i connect this fastsitephp app to this domain i am only able to run it with `php -S localhost` or `php -S my_server_ip:port` but using these i am not able to load up the app in a specific domain that is connected to my server

please help me with the ngxin config !!
even tried the .sh installer file but it only messed up the existing config file and crached all other domains connected to my server so not intrested in running that file again !!!! 😂😂

please help me with connecting the app to a domain.

**Comment by ConradSollitt** [comment]
Greetings,

The `.sh` installer is intended only for new servers running Ubuntu.

Are you able to share the nginx config and setup here? If you cannot share it publicly and are still having issues you can contact me from one of the social sites I'm on - links on my main website: https://conradsollitt.com/ 

On the main server for FastSitePHP I am using nginx with 5 different domains (including sub-domains). You can see the config here:
https://github.com/fastsitephp/fastsitephp/blob/master/docs/server-setup/nginx-config.txt

Commands for setting up the server are located here:
https://github.com/fastsitephp/fastsitephp/blob/master/docs/server-setup/server-setup.sh

From the above link here is where I setup the nginx config:

```sh
# Define nginx Settings
nano nginx-config.txt
# Copy file contents from [nginx-config.txt] and save
# Save using (this applies to all `nano` commands):
#    {control+s} -> {control+x}
sudo cp nginx-config.txt /etc/nginx/sites-available/multi-site
sudo ln -s /etc/nginx/sites-available/multi-site /etc/nginx/sites-enabled/
sudo rm /etc/nginx/sites-enabled/default
rm nginx-config.txt
```

Then later in the doc I describe using certbox to install HTTPS
https://certbot.eff.org/instructions?ws=nginx&os=ubuntufocal

For the `.sh` installer you can see the nginx config defined from the code here:
https://github.com/fastsitephp/fastsitephp/blob/master/scripts/shell/bash/create-fast-site.sh#L316

Without seeing your config file I would recommend looking to see if the file `/etc/nginx/sites-available/fastsitephp` exists. If it does it was installed by the installer and your previous config would likely exist in another file.

For the used config file look for lines starting with `server_name` and make sure they point to the domain you are setting up. For example, on the main FastSitePHP site I use `server_name fastsitephp.com www.fastsitephp.com;` so both www and non-www work the playground API service uses `server_name playground.fastsitephp.com;`.

**Comment by mrbeandev** [comment]
my doubt is that if i am setting the root directory as `root /var/www/mysite.com/` and i have installed the fastsitephp with composer in that same direcotry `/var/www/mysite.com/`. what next should i do ??

i have a index.php file from your examples :
```
<?php

require 'vendor/autoload.php';

$app = new \FastSitePHP\Application();
$app->setup('UTC');

$app->get('/', function() {
    return 'Hello World!';
});

$app->get('/site', function() use ($app) {
    return [
        'rootUrl' => $app->rootUrl(),
        'rootDir' => $app->rootDir(),
        'requestedPath' => $app->requestedPath(),
    ];
});

$app->get('/cached-file', function() {
    $file_path = __FILE__;
    $res = new \FastSitePHP\Web\Response();
    return $res->file($file_path, 'text', 'etag:md5', 'private');
});

$app->get('/whats-my-ip', function() {
    $req = new \FastSitePHP\Web\Request();
    return [
        'ipAddress' => $req->clientIp('from proxy', 'trust local'),
    ];
})
->filter(function() use ($app) {
    $app
        ->noCache()
        ->cors('*');
});

$app->run();
```

i am using this code and when i visit `mysite.com/whats-my-ip` this is what i see 
![image](https://user-images.githubusercontent.com/34623886/202694993-e92bf77c-06ce-4ba2-ab0d-30ef77f30aab.png)

and its working fine when i visit `/`  
<img width="284" alt="image" src="https://user-images.githubusercontent.com/34623886/202695153-9973f0c0-ec86-42b7-b889-04292594698a.png">


so where is the problem ?

this is my nginx config for this domain
```
server {
    server_name domain.dev;
    root /var/www/domain.dev;

    access_log /var/log/nginx/access.log;
    error_log /var/www/domain.dev/error.log;

    index index.php  index.html;

    location ~ \.php$ {
        include snippets/fastcgi-php.conf;
        fastcgi_pass unix:/run/php/php7.3-fpm.sock;
    }

    location / {
        try_files $uri $uri/ $uri.php?$args;
    }

    location ~ /\.ht {
		deny all;
	}

    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/domain.dev/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/domain.dev/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

}
```
`i am actually using a sub domain in the above config i didnt reveal what my real domain is or what my subdomain is.`

**Comment by ConradSollitt** [comment]
Hi @mrbeandev 

I'm sorry for the delay in getting back to you. If you still need help I'll make sure to respond quickly this week and I can also help with detailed testing including modify the Framework code to help solve the issue.

At a glance here are several items to try:

Have you specified the `sub-domain` in the `server_name` property?:
```
    server_name sub.domain.dev;
```

In my successful server setups I see that I have always specified `location /` before `location ~ \.php$`; I currently do not recall nginx priority order for these rules but but it's a difference I noticed.
```
	location / {
		try_files $uri $uri/ /index.php$is_args$args;
	}            
	location ~ \.php$ {
		include snippets/fastcgi-php.conf;
		fastcgi_pass unix:/var/run/php/php7.3-fpm.sock;
	}
```

FastSitePHP is designed to handle many different scenarios for server setup (Linux Main Domain, Sub-domain, IIS Main Site, Sub-Directory, etc). If you are still working on this and have trouble please let me know the OS and nginx version so I can try to replicate the issue.

**Comment by ConradSollitt** [comment]
Closing this out. If you need additional help please let me know.
